### PR TITLE
fix(minifront): #1598: display non-native-fee-warning per account

### LINKED ISSUE #1598: The NonNativeFeeWarning  is never displayed
**Describe the bug**
The [NonNativeFeeWarning](https://github.com/penumbra-zone/web/blob/6171ff97bc69262ae7a7e19c1c00ff36df6a0eef/apps/minifront/src/components/shared/non-native-fee-warning.tsx#L33)  is never displayed 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #1598

Checks if user has UM token in the same account as the selected source token

https://github.com/user-attachments/assets/7933599f-c555-4673-97c9-805404334fab

### CODE REVIEW

**Comment by Valentine1898** [comment]
That can be confusing for users because not every asset can be an alt fee asset 
In your demo TestUSD is not an alt fee asset, and it is not the case when a non-native fee asset is used

**Comment by VanishMax** [comment]
@Valentine1898 do I get it right that, if user has TestUSD (non-alt token) and, let's say, AltUSD (some alt token), and the source token is TestUSD, the fees will still be paid in AltUSD, if the amount is enough to cover the fees?

**Comment by Valentine1898** [comment]
> @Valentine1898 do I get it right that, if user has TestUSD (non-alt token) and, let's say, AltUSD (some alt token), and the source token is TestUSD, the fees will still be paid in AltUSD, if the amount is enough to cover the fees?

Yes, that's right

**Comment by VanishMax** [comment]
@Valentine1898 @TalDerei I implemented the checks for alt token balances before showing the NonNativeFeeWarning, mainly copied the logic from `getAssetFromGasPriceTable` service function. Ready for review.

Right now, `viewClient.gasPrices({})` returns empty array of `altGasPrices` for both testnet and penumbra-1. Any idea how to test it locally?

**Comment by TalDerei** [comment]
> Right now, `viewClient.gasPrices({})` returns empty array of `altGasPrices` for both testnet and penumbra-1. Any idea how to test it locally?

add this code block inside the [block processor](https://github.com/penumbra-zone/web/blob/main/packages/query/src/block-processor.ts#L141) and resync, then check updated `GasPrices` table.

```
const assetId1 = new AssetId({
      inner: base64ToUint8Array("drPksQaBNYwSOzgfkGOEdrd4kEDkeALeh58Ps+7cjQs=")
    });

    const assetId2 = new AssetId({
      inner: base64ToUint8Array("B+9mATKkwyNfqyctQ9m5dSqDN7LRCFl6v/r/XyRtDw8=")
    });

    const assetId3 = new AssetId({
      inner: base64ToUint8Array("KSOgqHs6JCHxZcyFPb9zqb2vtdoNlIVktgWcsCF8RAc=")
    });

    await this.indexedDb.saveGasPrices(
      new GasPrices({
        assetId: this.stakingAssetId,
        blockSpacePrice: 60n,
        compactBlockSpacePrice: 1556n,
        verificationPrice: 1n,
        executionPrice: 1n
      }),
    );

    await this.indexedDb.saveGasPrices(
      new GasPrices({
        assetId: assetId1,
        blockSpacePrice: 600n,
        compactBlockSpacePrice: 15560n,
        verificationPrice: 10n,
        executionPrice: 10n
      }),
    );

    await this.indexedDb.saveGasPrices(
      new GasPrices({
        assetId: assetId2,
        blockSpacePrice: 120n,
        compactBlockSpacePrice: 3112n,
        verificationPrice: 2n,
        executionPrice: 2n
      }),
    );

    await this.indexedDb.saveGasPrices(
      new GasPrices({
        assetId: assetId3,
        blockSpacePrice: 1200n,
        compactBlockSpacePrice: 31120n,
        verificationPrice: 20n,
        executionPrice: 20n
      }),
    );

    await this.indexedDb.saveGasPrices(
      new GasPrices({
        assetId: this.stakingAssetId,
        blockSpacePrice: 60n,
        compactBlockSpacePrice: 1556n,
        verificationPrice: 1n,
        executionPrice: 1n
      }),
    );
```

**Comment by Valentine1898** [comment]
@VanishMax 
It's an RPC bug, here's the fix
https://github.com/penumbra-zone/web/pull/1626

**Comment by Valentine1898** [comment]
Please rebase on main, I'll review later today

**Comment by VanishMax** [comment]
@Valentine1898 Updated demo where I added TestUSD to the alt tokens in IndexedDB and showing 3 cases:
1. Account 10 with TestUSD and no UM tokens – warning shows correctly
2. Account 12 with Osmo (not an alt token) – no warning as user can't pay for alt fees this way (we might consider adding validation for this case later)
3. Account 0 (with UM tokens) with GN – no warning as UM will be used to pay for the fees

https://github.com/user-attachments/assets/8b119ac0-a950-4164-b774-098fc66ac6af

**Comment by TalDerei** [comment]
> @Valentine1898 Updated demo where I added TestUSD to the alt tokens in IndexedDB and showing 3 cases:

these seem like the proper expected cases to me 👍

File: apps/minifront/src/components/shared/non-native-fee-warning.tsx [hunk 1]
```diff
@@ -1,38 +1,105 @@
...
+      getAssetIdFromValueView
+        .optional()(asset.balanceView)
+        ?.equals(getAssetId.optional()(stakingAssetMetadata)) &&
+      getAddressIndex.optional()(asset)?.account === account,
   );
 };
 
-export const useShouldRender = (balancesResponses: BalancesResponse[] = [], amount: number) => {
+// Finds the alt tokens in the user's account balances that can be used for fees
+const hasAltToken = (
```
Comment (TalDerei) [inline apps/minifront/src/components/shared/non-native-fee-warning.tsx:31]: can we combine `hasStakingToken` and `hasAltToken` into [hasTokenBalance](https://github.com/penumbra-zone/web/blob/main/packages/storage/src/indexed-db/index.ts#L872)?

File: apps/minifront/src/components/shared/non-native-fee-warning.tsx [hunk 2]
```diff
@@ -1,38 +1,105 @@
...
   const stakingTokenMetadata = useStakingTokenMetadata();
-  const userHasStakingToken = hasStakingToken(balancesResponses, stakingTokenMetadata.data);
-  const showNonNativeFeeWarning = amount > 0 && !userHasStakingToken;
 
-  return showNonNativeFeeWarning;
+  if (!amount) {
+    return false;
+  }
+
+  const sourceAddressIndex = getAddressIndex.optional()(account)?.account ?? 0;
```
Comment (TalDerei) [inline apps/minifront/src/components/shared/non-native-fee-warning.tsx:80]: why do we have a default value for source here?

File: apps/minifront/src/components/shared/non-native-fee-warning.tsx [hunk 3]
```diff
@@ -1,38 +1,105 @@
...
 };
 
 /**
- * Renders a non-native fee warning if A) the user does not have any balance of
- * the staking token to use for fees, and B) the amount the user has entered for
- * a transaction (e.g., send or swap) is nonzero -- i.e., a fee will be
- * required.
+ * Renders a non-native fee warning if
+ * 1. the user does not have any balance (in the selected account) of the staking token to use for fees
+ * 2. user has alt token balances to pay for the fees
```
Comment (TalDerei) [inline apps/minifront/src/components/shared/non-native-fee-warning.tsx:97]: "The user does not have sufficient balances in alternative tokens to cover the fees."

File: apps/minifront/src/components/shared/non-native-fee-warning.tsx (hunk 2 above)
Comment (TalDerei) [reply apps/minifront/src/components/shared/non-native-fee-warning.tsx:80]: cc @Valentine1898

File: apps/minifront/src/components/shared/non-native-fee-warning.tsx (hunk 1 above)
Comment (VanishMax) [reply apps/minifront/src/components/shared/non-native-fee-warning.tsx]: refactored the code now + removed `useShouldRender` since there's no need in it after creating `hasTokenBalance`

**Review by TalDerei — APPROVED** [review]
