### PR TITLE
fix: lazy-load the skip widget, saving a lot of time

### LINKED ISSUE #2311: Improve load time of Portfolio page.
We need to improve the loading time for the portfolio page.

### PR DESCRIPTION
**Pull request by vacekj**
fixes #2311 

Current fixes:
- Lazy-load the skip widget, speeding up the page load significantly.

### CODE REVIEW

File: apps/veil/src/pages/portfolio/ui/shield-unshield.tsx [hunk 1]
```diff
@@ -1,14 +1,16 @@
...
-import { useEffect, useState, useMemo } from 'react';
+import { useEffect, useState, useMemo, lazy, Suspense } from 'react';
 import { X } from 'lucide-react';
 import { useRegistry } from '@/shared/api/registry.ts';
 import { getMetadata } from '@penumbra-zone/getters/value-view';
 import { theme as penumbraTheme } from '@penumbra-zone/ui/theme';
 import { UnshieldDialog } from '@/pages/portfolio/ui/unshield-dialog.tsx';
 
+// Use React.lazy for the Widget
+const LazySkipWidget = lazy(() => import('@skip-go/widget').then(mod => ({ default: mod.Widget })));
```
Comment (JasonMHasperhoven) [inline apps/veil/src/pages/portfolio/ui/shield-unshield.tsx:12]: Not a big difference, but you can also use dynamic from `next/dynamic` to one line it (No suspense needed)

Comment (vacekj) [reply apps/veil/src/pages/portfolio/ui/shield-unshield.tsx:12]: Tried that, hit a bug in next with ESM and CJS, found a blog post that also hit it. This works just as well

**Review by erwanor — APPROVED** [review]
It's faster, let's merge?
