### PR TITLE
fix(veil): #2437: vote percentage round

### LINKED ISSUE #2437: LQT: round percentages
Check if all percentage values in the tournament page are rounded

Image

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #2437 

Additionally, this PR uses Link component instead of programmatic routing in delegator history tables and fixes asset icon display in delegator voting rewards. Previously, all assets were unknown like here:

image

Now, it renders like this:

image

Some old assets are undefined. I think it was before the switch to phobos-3 chainId, – all assets had different ids

### CODE REVIEW

File: apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx [hunk 1]
```diff
@@ -32,9 +35,21 @@ interface VotingRewardsRowProps {
...
+      className='grid grid-cols-subgrid col-span-4 hover:bg-action-hoverOverlay'
+      href={`/tournament/${row.epoch}`}
+    >
       <TableCell cell>{`Epoch #${row.epoch}`}</TableCell>
-      <RewardCell reward={row} />
+      <TableCell cell>
+        <span className='font-mono whitespace-pre'>
+          {round({
+            value: (row.power / row.summary.total_voting_power) * 100,
+            decimals: 2,
```
Comment (TalDerei) [inline apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx:47]: suggestion: 3 decimal places to match figma

File: apps/veil/src/pages/tournament/ui/vote.tsx [hunk 2]
```diff
@@ -13,7 +14,7 @@ export const Vote = ({ asset, percent, hideFor }: VoteProps) => {
     <div className='flex items-center gap-1'>
       <AssetIcon metadata={asset} />
       <Text smallTechnical color='text.primary'>
-        {percent * 100}% {hideFor ? '' : 'for'}
+        {round({ value: percent * 100, decimals: 2 })}% {hideFor ? '' : 'for'}
```
Comment (TalDerei) [inline apps/veil/src/pages/tournament/ui/vote.tsx:17]: suggestion: 3 decimal places to match figma

File: apps/veil/src/pages/tournament/server/delegator-history.ts [hunk 3]
```diff
@@ -87,7 +89,13 @@ const tournamentDelegatorHistoryQuery = async ({
       jsonArrayFrom(
         eb
           .selectFrom(filteredQuery.as('delegators'))
-          .selectAll()
+          .select(exp => [
+            'epoch',
+            'power',
+            'reward',
+            'address',
+            sql<string>`encode(${exp.ref('asset_id')}, 'base64')`.as('asset_id'),
```
Comment (TalDerei) [inline apps/veil/src/pages/tournament/server/delegator-history.ts:97]: comment: good catch

**Review by TalDerei — APPROVED** [review]
good restructuring here, this looks good to me 👍
