### PR TITLE
1555 cannot end and withdraw auction from accounts other than 0 account

### LINKED ISSUE #1555: Cannot end and withdraw auction from accounts other than 0 account
**Describe the bug**
If you create an auction from any other account other than account 0, you will not be able to end that auction and will get an error 
image

https://github.com/penumbra-zone/web/blob/5cac34fbb65b69569c694a268d0066fac6a94912/apps/minifront/src/state/swap/dutch-auction/index.ts#L179-L180

This is because getting `source` from `swap.assetIn` doesn't work and `source=0` will always be used

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Valentine1898**
closes #1555

### CODE REVIEW

File: packages/ui/components/ui/dutch-auction-component/expanded-details/index.tsx [hunk 1]
```diff
@@ -104,6 +107,12 @@ export const ExpandedDetails = ({
           <AuctionIdComponent auctionId={auctionId} />
         </Row>
       )}
+
+      {addressIndex && (
+        <Row label='Account'>
+          <span className='font-mono text-xs'>{addressIndex.account}</span>
+        </Row>
+      )}
```
Comment (Valentine1898) [inline packages/ui/components/ui/dutch-auction-component/expanded-details/index.tsx:115]: Before: 
image
After:
image

File: apps/minifront/src/state/swap/dutch-auction/index.ts [hunk 2]
```diff
@@ -175,18 +179,19 @@ export const createDutchAuctionSlice = (): SliceCreator<DutchAuctionSlice> => (s
     }
   },
 
-  endAuction: async auctionId => {
-    const source = getAddressIndex.optional()(get().swap.assetIn);
-    const req = new TransactionPlannerRequest({ dutchAuctionEndActions: [{ auctionId }], source });
+  endAuction: async (auctionId, addressIndex) => {
+    const req = new TransactionPlannerRequest({
+      dutchAuctionEndActions: [{ auctionId }],
+      source: addressIndex,
```
Comment (TalDerei) [inline apps/minifront/src/state/swap/dutch-auction/index.ts:185]: ack. passing in the `addressIndex` rather than fetching it from the swap information makes sense.

**Comment by Valentine1898** [comment]
I have no idea why CI is broken

**Comment by TalDerei** [comment]
> I have no idea why CI is broken

same with #1560

**Comment by grod220** [comment]
A new version of Rust was shipped. Do `rustup update` locally. It looks like we have a dep with a build issue. We should create a new PR to fix this to unblock work.

**Review by grod220 — APPROVED** [review]
Nice catch!

**Review by TalDerei — APPROVED** [review]
