### PR TITLE
fix(veil): #2350: personal rewards tables

### LINKED ISSUE #2350: rendering rewards lagging
a [conditional](https://github.com/penumbra-zone/web/blob/main/apps/veil/src/pages/tournament/ui/total-delegator-rewards.tsx#L95) was removed during the refactor of https://github.com/penumbra-zone/web/pull/2332 that prevented rewards briefly displaying as zero before rendering the correct amount.

additionally, "no voting rewards found for this account" was [accidentally removed](https://github.com/penumbra-zone/web/pull/2332/files#diff-7ca50a7b5908d778409d54be927510ac77a5f259b8d55feef970a0d2ced23b4aL72-L75) and should be restored. We can also add a similar message for zero reward positions. cc @cronokirby 

additionally, the the loading states for paginating between states seems to have been affected post refactor.

-----------------------

https://github.com/user-attachments/assets/be06ff4a-8af7-4e5c-a1af-dd32a6f3786d

https://github.com/user-attachments/assets/dbbc9285-ff30-4e99-8899-147ebdc913f5

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #2350 

In this PR:
1. Fix: Returned correct loading and empty states to "LPs rewards" and "Voting rewards" tables within the tournament landing page, as the issue suggests
2. Feat: added sorting by rewards, not only by epoch to "Voting rewards" table. Previously, only sorting by epoch was supported
3. Refactor: removed all JS-based rewards and power calculation from the server, delegated this logic to SQL. Works faster now, easier to maintain and read. Tested that the result is the same as it was before.
4. Fixed a bug of pagination limit not being correctly applied in the voting rewards table

image

### CODE REVIEW

File: apps/veil/src/pages/tournament/server/delegator-history.ts [hunk 1]
```diff
@@ -32,162 +31,118 @@ export interface TournamentDelegatorHistoryResponse {
...
- * delegator address.
- *
- * For each epoch we:
- *    * filter rows belonging to the delegator,
- *    * tally their total voting power,
- *    * capture that epoch’s reward and asset id.
- *
- * Finally, we aggregate the rewards earned by the address across all epochs.
- */
-function processEpochResults(
```
Comment (VanishMax) [inline apps/veil/src/pages/tournament/server/delegator-history.ts:59]: removed this function completely in favor of vanilla SQL calculations

File: apps/veil/src/pages/tournament/server/delegator-history.ts [hunk 2]
```diff
@@ -32,162 +31,118 @@ export interface TournamentDelegatorHistoryResponse {
...
-  const registryClient = new ChainRegistryClient();
-  const registry = await registryClient.remote.get(chainId);
-
-  // Map only the paginated results with metadata
-  const mapped = await Promise.all(
-    paginatedResults.map(item => {
-      // TODO: remove hardcoded staking asset metadata when registry is fixed.
-      const stakingAssetId = registryClient.bundled.globals().stakingAssetId;
-      const asset_id = new AssetId({ inner: Uint8Array.from(item.asset_id) });
-      const metadata = registry.tryGetMetadata(stakingAssetId);
```
Comment (VanishMax) [inline apps/veil/src/pages/tournament/server/delegator-history.ts:169]: removed metadata searching from the backend as frontend duplicates this work anyway

File: apps/veil/src/pages/tournament/ui/previous-epochs.tsx [hunk 3]
```diff
@@ -84,26 +84,27 @@ const PreviousEpochsRow = observer(
             </Tooltip>
           )}
         </TableCell>
-        {connected && (rewardsLoading || reward !== undefined) && (
-          <TableCell cell loading={isLoading || rewardsLoading}>
```
Comment (VanishMax) [inline apps/veil/src/pages/tournament/ui/previous-epochs.tsx:88]: found a rendering bug that was hiding a cell in a certain condition

File: apps/veil/src/pages/tournament/server/delegator-history.ts (hunk 1 above)
Comment (cronokirby) [reply apps/veil/src/pages/tournament/server/delegator-history.ts:59]: love this!

File: apps/veil/src/pages/tournament/api/use-personal-rewards.ts [hunk 4]
```diff
@@ -69,8 +70,7 @@ const fetchRewards = async (
       '/api/tournament/delegator-history',
       {
         epochs: Array.from(epochs),
-        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- address is defined
-        address: { inner: Array.from(address!.inner) },
+        address: address ? bech32mAddress(address) : '',
```
Comment (cronokirby) [inline apps/veil/src/pages/tournament/api/use-personal-rewards.ts:73]: I think we should throw here, or explicitly mark this function as being able to return undefined, because otherwise we'll just get an error when the server sees an empty string and doesn't like that.

File: apps/veil/src/pages/tournament/server/delegator-history.ts [hunk 5]
```diff
@@ -32,162 +31,118 @@ export interface TournamentDelegatorHistoryResponse {
...
-      asset_id: Buffer.from(match.assetId),
-      reward: match.reward,
-    });
+  const sortDirectionParam = body.sortDirection;
+  const sortDirection =
+    sortDirectionParam && DIRECTIONS.includes(sortDirectionParam) ? sortDirectionParam : 'desc';
 
-    totalReward += match.reward;
+  const epochs = Array.isArray(body.epochs)
+    ? body.epochs.filter(epoch => typeof epoch === 'string')
```
Comment (cronokirby) [inline apps/veil/src/pages/tournament/server/delegator-history.ts:52]: Generally not a fan of doing `typeof` comparisons instead of explicitly comparing to undefined, because it creates unnecessary code churn if the type changes.

File: apps/veil/src/pages/tournament/server/delegator-history.ts [hunk 6]
```diff
@@ -32,162 +31,118 @@ export interface TournamentDelegatorHistoryResponse {
...
+    : [];
+
+  if (!isAddress(body.address)) {
+    return 'Invalid address';
   }
```
Comment (cronokirby) [inline apps/veil/src/pages/tournament/server/delegator-history.ts:57]: Instead of doing a check like this, we should instead transform the type so that it's an actual Address type. This isn't blocking though, but a point to think of when we refactor the domain type library and what not.

File: apps/veil/src/pages/tournament/ui/lp-rewards.tsx [hunk 7]
```diff
@@ -1,86 +1,77 @@
...
-            null
-          </TableCell>
-          <TableCell cell loading>
-            null
-          </TableCell>
-        </div>
-      ))}
-    </>
-  );
-}
```
Comment (cronokirby) [inline apps/veil/src/pages/tournament/ui/lp-rewards.tsx:49]: This was explicitly factored out, because the pattern of merging in `isLoading` deep down into a component's display makes it much harder to figure out what the component is actually display as it goes through distinct states in its lifecycle.

The modification here should just be to add the case for when the rewards are known to be 0.

File: apps/veil/src/pages/tournament/ui/previous-epochs.tsx (hunk 3 above)
Comment (cronokirby) [reply apps/veil/src/pages/tournament/ui/previous-epochs.tsx:88]: This illustrates my gripe against nesting the loading condition inside of the component, versus making a top level decision.

**Review by cronokirby — CHANGES_REQUESTED** [review]
In `lp-rewards.tsx`, I think we should keep a separate LoadingRows construction. Maybe the way it's done in `total-delegator-rewards`, for example.

The other comments are minor.

File: apps/veil/src/pages/tournament/api/use-personal-rewards.ts (hunk 4 above)
Comment (VanishMax) [reply apps/veil/src/pages/tournament/api/use-personal-rewards.ts:73]: the endpoint throws 400 in this rare case, so it's handled

File: apps/veil/src/pages/tournament/ui/lp-rewards.tsx (hunk 7 above)
Comment (VanishMax) [reply apps/veil/src/pages/tournament/ui/lp-rewards.tsx:49]: How blocking this change is? Didn't hear from the web team that pattern was bad.

I suggest sticking to the [Conventional Comments](https://conventionalcomments.org/) when doing code reviews – it generally helps preventing subjective change requests and promotes discussion rather then submission to another opinion. Sticking to conventional comments, what label would you put on this comment? How blocking would you make it?

Comment (VanishMax) [reply apps/veil/src/pages/tournament/ui/lp-rewards.tsx:49]: In retrospect, I see the concern – been trying to refactor the refactored, erasing your code while doing so. Will change it tomorrow

Comment (cronokirby) [reply apps/veil/src/pages/tournament/ui/lp-rewards.tsx:49]: I would consider this a blocking suggestion. I think we've already run into a couple of bugs related to unclear handling of what is and isn't loading, so I think we should apply a soft "ratchet" of at least not regressing in terms of our handling of this.

This doesn't directly impact the current functionality, but it makes any kind of bug finding wrt the lifecycle much more tedious, in our recent experience.

File: apps/veil/src/pages/tournament/api/use-personal-rewards.ts (hunk 4 above)
Comment (cronokirby) [reply apps/veil/src/pages/tournament/api/use-personal-rewards.ts:73]: Yeah, I guess it's fine to defer to the endpoint

File: apps/veil/src/pages/tournament/ui/lp-rewards.tsx (hunk 7 above)
Comment (JasonMHasperhoven) [reply apps/veil/src/pages/tournament/ui/lp-rewards.tsx:49]: That's nice :+1:

**Review by cronokirby — APPROVED** [review]

File: apps/veil/src/pages/tournament/ui/lp-rewards.tsx [hunk 8]
```diff
@@ -151,20 +127,25 @@ export const LpRewards = observer(() => {
...
-              <LpRewardRow key={index} lpReward={lpReward} umMetadata={umMetadata} />
-            ))
+          {!loading && !total && (
+            <div className='col-span-5 text-sm text-muted-foreground py-4'>
+              No LP rewards found for this account.
+            </div>
           )}
+
+          {loading &&
+            new Array(BASE_LIMIT).fill({}).map((_, index) => <LoadingRow cells={5} key={index} />)}
```
[the remark this answers is not in the document]
Comment (VanishMax) [reply apps/veil/src/pages/tournament/ui/lp-rewards.tsx:137]: I'd leave it for a parent component to deal with, at least for now
