### PR TITLE
fix: lints and assertions

### LINKED ISSUE #2308: Uncaught error destructing property of address
**Describe the bug**
In both dev and prod, I'm encountering an error that logs to console:

> `error-boundary-callbacks.js:83 Uncaught Error: Cannot destructure property 'address' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.`

which I encountered on this route: http://localhost:3000/portfolio

**To Reproduce**`

1. Run dev env 
2. Navigate to http://localhost:3000/portfolio
3. Wait; you don't even need to click, I don't think, just wait

**Expected behavior**
I expect the page to load so that I can interact with the website.

**Screenshots**

Image

**Additional context**
May or may not be related to LQT schema changes (#2306). I suspect that it's not, and the bug slipped in during a recent merge, but that's just a supposition at this point.

### PR DESCRIPTION
**Pull request by vacekj**
fixes #2308 

addresses the destructuring error, plus cleans up some other lints and type assertions.

### CODE REVIEW

**Comment by TalDerei** [comment]
@vacekj does the scope here consume https://github.com/penumbra-zone/web/issues/2314 as well?

**Comment by TalDerei** [comment]
> @vacekj does the scope here consume #2314 as well?

I audited the other non-null assertions instances and they seem safe to me. all good there

File: apps/veil/src/features/cosmos/cosmos-connect-button.tsx [hunk 1]
```diff
@@ -20,27 +20,24 @@ const CosmosConnectButtonInner = observer(
...
     );
     const chains = useChains(penumbraIbcChains);
-    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- Osmosis is always available
-    const { address, disconnect, openView, isWalletConnected } = (chains['osmosis'] ??
-      chains['osmosistestnet'])!;
 
-    const handleConnect = () => {
-      openView();
-    };
+    const availableChain = Object.keys(chains)[0];
```
Comment (TalDerei) [inline apps/veil/src/features/cosmos/cosmos-connect-button.tsx:24]: comment: any idea why `availableChain` is returning undefined for me on localhost? It's prevents me from connecting my cosmos wallet?

File: apps/veil/src/pages/portfolio/ui/onboarding.tsx [hunk 2]
```diff
@@ -69,92 +67,8 @@ export const Onboarding = observer(() => {
     return null;
   }
 
-  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition -- temporary
-  if (isPhase2) {
```
Comment (TalDerei) [inline apps/veil/src/pages/portfolio/ui/onboarding.tsx:73]: comment: remind me, what was this flag for? @JasonMHasperhoven

File: apps/veil/src/features/cosmos/cosmos-connect-button.tsx [hunk 3]
```diff
@@ -20,27 +20,24 @@ const CosmosConnectButtonInner = observer(
...
+
+    const { address, disconnect, openView, isWalletConnected } = chains[availableChain ?? ''] ?? {};
```
Comment (TalDerei) [inline apps/veil/src/features/cosmos/cosmos-connect-button.tsx:26]: 👍

File: apps/veil/src/pages/portfolio/ui/onboarding.tsx [hunk 4]
```diff
@@ -219,27 +141,10 @@ export const Onboarding = observer(() => {
...
-                  window.open(
-                    'https://app.penumbra.zone/#/deposit/skip',
-                    '_blank',
-                    'noopener,noreferrer',
-                  );
-                }}
-              >
-                Go to App
-              </Button>
-            }
```
Comment (TalDerei) [inline apps/veil/src/pages/portfolio/ui/onboarding.tsx:239]: comment: ACK – removed skip link from onboarding guide

File: apps/veil/src/pages/portfolio/ui/onboarding.tsx [hunk 5]
```diff
@@ -69,92 +67,8 @@ export const Onboarding = observer(() => {
...
-            />
-          </div>
-        </div>
-      </PortfolioCard>
-    );
-  }
-
   return (
-    <Card>
+    <PortfolioCard>
```
Comment (TalDerei) [inline apps/veil/src/pages/portfolio/ui/onboarding.tsx:71]: comment: ACK – moved portfolio card down

**Review by TalDerei — APPROVED** [review]
left some minor questions, otherwise looks good

**Comment by TalDerei** [comment]
can we make this a unique key (https://github.com/penumbra-zone/web/blob/main/apps/veil/src/pages/portfolio/ui/asset-bars.tsx#L180)? 

------

Screenshot 2025-05-04 at 10 08 55 PM

**Comment by conorsch** [comment]
Tested locally via dev env, and I'm no longer seeing a crash on the `/portfolio` route. That's great! Looking forward to this one landing.
