### PR TITLE
Fix layout and resizing issues in the extension popup

### LINKED ISSUE #779: Popup should handle resizing
https://discord.com/channels/824484045370818580/1044457038886998137/1218538710736437348

### PR DESCRIPTION
**Pull request by jessepinho**
Explanation for changes are inline. In short:
- I made the popup root div have a _min_ width/height instead of a hard-coded width/height, thus allowing it to scale with the popup window size.
- I fixed the issue where the scrollbars were hidden behind the fixed-position approve/deny buttons, by removing the fixed positioning and using flexbox instead.
- You may notice in the screencap that there is still some strange scrolling behavior when you shrink the window _below_ 400px wide or 600px tall. That's due to the min widths that we apparently need for the attached window height. I believe that, to work around this, we'd need to make a separate root for detached vs. attached popup windows. We could do that, but I'd suggest we make that a separate PR (if reviewers even think it's necessary), since that'll require quite a bit of extra work.

https://github.com/penumbra-zone/web/assets/1121544/f30622fc-3798-4e04-bca1-6c440c31509c

Closes #779

### CODE REVIEW

File: apps/extension/src/routes/popup/approval/origin.tsx [hunk 1]
```diff
@@ -100,13 +100,16 @@ export const OriginApproval = () => {
...
         </div>
-        <ApproveDeny
-          variants={['gradient']}
-          approve={approve}
-          deny={deny}
-          ignore={lastRequest && ignore}
-          wait={3}
-        />
+
+        <div className='flex grow flex-col justify-end'>
```
Comment (jessepinho) [inline apps/extension/src/routes/popup/approval/origin.tsx:104]: Pushes the Approve/Deny buttons all the way to the bottom of the window without having to use `position: fixed`

File: apps/extension/src/routes/popup/approval/approve-deny.tsx [hunk 2]
```diff
@@ -19,7 +19,7 @@ export const ApproveDeny = ({
   useEffect(startCountdown, [startCountdown]);
 
   return (
-    <div className='fixed inset-x-0 bottom-0 flex flex-row flex-wrap justify-center gap-4 bg-black p-4 shadow-lg'>
```
Comment (jessepinho) [inline apps/extension/src/routes/popup/approval/approve-deny.tsx:22]: Now, this div will only go up to where the approve/deny buttons are, so the scroll bar no longer goes behind them.

File: apps/extension/src/routes/popup/approval/transaction/index.tsx [hunk 3]
```diff
@@ -32,8 +32,8 @@ export const TransactionApproval = () => {
   };
 
   return (
-    <div className='flex h-screen flex-col justify-between'>
-      <div className='grow overflow-auto p-[30px] pb-44 pt-10'>
+    <div className='flex h-screen flex-col'>
+      <div className='grow overflow-auto p-[30px] pt-10'>
```
Comment (jessepinho) [inline apps/extension/src/routes/popup/approval/transaction/index.tsx:36]: This pushes the approve/deny buttons to the button using flex box

File: apps/extension/src/routes/popup/popup-layout.tsx [hunk 4]
```diff
@@ -12,7 +12,7 @@ import { Outlet } from 'react-router-dom';
  * then removing the hard-coded width from `globals.css`.
  */
 export const PopupLayout = () => (
-  <div className='flex min-h-full flex-col bg-card-radial'>
+  <div className='flex grow flex-col bg-card-radial'>
```
Comment (jessepinho) [inline apps/extension/src/routes/popup/popup-layout.tsx:15]: Not sure why `height: 100%` doesn't fill a flexbox, but apparently it doesn't. So I had to use `grow` instead.

File: packages/ui/styles/globals.css [hunk 5]
```diff
@@ -59,8 +59,11 @@
   }
 
   #popup-root {
-    width: 400px;
-    height: 600px;
+    min-width: 400px;
+    min-height: 600px;
+    height: 100%;
+    display: flex;
+    flex-direction: column;
```
Comment (jessepinho) [inline packages/ui/styles/globals.css:66]: `min-height` makes the attached popup the correct size, but doesn't restrict the root div from growing larger in the detached popup.

**Review by TalDerei — APPROVED** [review]
