### PR TITLE
fix(veil): #2598: eliminate layout shifts in portfolio page

### LINKED ISSUE #2598: Unreliable connection status handling
After calling [setup()](https://github.com/penumbra-zone/web/blob/12e187ced3d7aea9aa56e30be3d9d01155d0bbe4/apps/veil/src/shared/model/connection/index.ts#L15), connected is false by default. If there's no connection, it stays that way; if there is, a callback updates it.

This creates a UX issue: there's no reliable way to know when connection status has been resolved. Setting loading = false too early causes a flash of “please connect,” while waiting on the callback can hang forever if not connected. We likely need a separate “checked” flag to resolve this cleanly.

-----------

https://github.com/user-attachments/assets/4477f7e7-a0eb-432e-89cd-da2f7147635a

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #2598 

After looking at the #2598 issue, I found that the UX issue won't be fixed by adding new state in the connection store, rather the portfolio page needed a major rework to eliminate content layout shift and jumps.

In this PR, I used `connectedLoading` variable introduced by @cronokirby to render better connection states in the header and in the portfolio pages. Here's the final result in a video – compare it with [how it was before](https://github.com/user-attachments/assets/4477f7e7-a0eb-432e-89cd-da2f7147635a).

I also fixed css issues here and there while working on portfolio page.

https://github.com/user-attachments/assets/8b85176d-fc0c-4ff5-97be-3bc58106c95f

### CODE REVIEW

File: apps/veil/src/pages/portfolio/index.tsx [hunk 1]
```diff
@@ -71,21 +73,33 @@ function MobilePortfolioPage() {
...
-        <WalletConnect />
+      {!isConnectionLoading && (
+        <div ref={parent} className='container mx-auto flex max-w-[1136px] flex-col gap-4 py-8'>
+          <WalletConnect />
 
-        {/* Asset Allocation Bars */}
-        {(isPenumbraConnected || isCosmosConnected) && <AssetBars />}
+          {/* Asset Allocation Bars */}
+          {(isPenumbraConnected || isCosmosConnected) && (
+            <PortfolioCard title={'Allocation'}>
```
Comment (TalDerei) [inline apps/veil/src/pages/portfolio/index.tsx:91]: comment: why was the `PortfolioCard` moved up the call stack here?

File: apps/veil/src/pages/portfolio/index.tsx [hunk 2]
```diff
@@ -71,21 +73,33 @@ function MobilePortfolioPage() {
 }
 
 const DesktopPortfolioPage = observer(() => {
-  const { isPenumbraConnected, isCosmosConnected } = useUnifiedAssets();
+  const [parent] = useAutoAnimate();
```
Comment (TalDerei) [inline apps/veil/src/pages/portfolio/index.tsx:76]: comment: ACK – `useAutoAnimate` placed at the top of the calling component in few places.

**Review by TalDerei — APPROVED** [review]
left some comments

File: apps/veil/src/pages/portfolio/index.tsx [hunk 3]
```diff
@@ -71,21 +73,33 @@ function MobilePortfolioPage() {
...
   return (
     <>
+      <PenumbraWaves />
+
       <ShieldingTicker />
-      <div className='container mx-auto flex max-w-[1136px] flex-col gap-4 py-8'>
-        <PenumbraWaves />
 
-        <WalletConnect />
+      {!isConnectionLoading && (
```
[the remark this answers is not in the document]
Comment (VanishMax) [reply apps/veil/src/pages/portfolio/index.tsx:85]: In my tests the wait is always less than a blink of an eye, that's why it was flashing a lot. I believe this is a worthy sacrifice
