### PR TITLE
fix: #1195: Hide the redundant scroll caused by long addresses

### LINKED ISSUE #1195: Delegation approval width bug 🐜
When making a delegation, the width of the approval window gets so large it requires horizontal scroll. Perhaps we need to make the validator identity key something that is truncated or has a wordbreak?

https://github.com/penumbra-zone/web/assets/16624263/44d49c15-7d06-4952-babf-c3dc6e860773

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #1195 

Screenshot of the problem:

image

### CODE REVIEW

**Comment by Valentine1898** [comment]
Can you add before and after screenshots to the PR? 
This would be very helpful for reviewers when it comes to UI changes

File: packages/ui/components/ui/tx/view/viewbox.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ export const ViewBox = ({ label, visibleContent, isOpaque }: ViewBoxProps) => {
   // if isOpaque is undefined, set it to !visibleContent
   isOpaque = isOpaque ?? !visibleContent;
   return (
-    <Box>
+    <Box className='overflow-hidden'>
```
Comment (grod220) [inline packages/ui/components/ui/tx/view/viewbox.tsx:20]: This is tricky, but we need a way to display the full validator address here (without the window extending beyond the view of the screen). It will be important that users can validate this on this screen. Perhaps it's something that can be clicked to expand?

Screenshot 2024-06-04 at 1 19 37 PM

Comment (VanishMax) [reply packages/ui/components/ui/tx/view/viewbox.tsx:20]: @grod220 @Valentine1898 Thanks for the comments. I added a picture of how it was before to the description of this PR. This time, I removed the `truncate` prop from the ActionDetails.Row component and created the ActionDetails.TruncatedText component that renders long text accessibly with keyboard navigation support.


https://github.com/penumbra-zone/web/assets/29180358/79cbaa59-67d1-46ce-8237-35c1ecc68851

**Comment by TalDerei** [comment]
@VanishMax just flagging if there are any PRs you want the entire web team to review, you can select `web-reviewers`

File: .changeset/old-candles-compete.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@penumbra-zone/ui': patch
```
Comment (grod220) [inline .changeset/old-candles-compete.md:2]: If we add new truncate functionality, think this would be a minor version bump

File: packages/ui/components/ui/box.tsx [hunk 3]
```diff
@@ -34,19 +34,21 @@ export const Box = ({
...
   layoutId,
   headerContent,
+  className,
 }: PropsWithChildren<
   VariantProps<typeof variants> & {
     label?: ReactNode;
     layout?: boolean;
     layoutId?: string;
     headerContent?: ReactNode;
+    className?: string;
```
Comment (grod220) [inline packages/ui/components/ui/box.tsx:44]: This has been one of the things that @jessepinho particularly has been hunting down to get rid of. By default, shadcn/ui takes a className-first kind of approach. This makes the consumer have more flexibility on passing any kind of style into the child. However, this also creates an API surface that is a bit more risky. Different parts our app can possibly customize too much. The solution we are converging toward is relying more upon variants and explicitly enumerated props passing.

In this case, we should find a way to accomplish the effect you are going for, but without requiring className as a prop.

File: packages/ui/components/ui/tx/view/undelegate.tsx [hunk 4]
```diff
@@ -27,8 +27,10 @@ export const UndelegateComponent = ({ value }: { value: Undelegate }) => {
 
           {/** @todo: Render validator name/etc. after fetching? */}
           {!!value.validatorIdentity && (
-            <ActionDetails.Row label='Validator identity' truncate>
-              {bech32mIdentityKey(value.validatorIdentity)}
+            <ActionDetails.Row label='Validator identity'>
+              <ActionDetails.TruncatedText>
```
Comment (grod220) [inline packages/ui/components/ui/tx/view/undelegate.tsx:31]: Nice, that's cool

File: packages/ui/components/ui/box.tsx (hunk 3 above)
Comment (VanishMax) [reply packages/ui/components/ui/box.tsx]: Right, got it. Changed to allow the `overflow` variant with type `xHidden` to the Box component, while removing className. Completely agree on the approach

**Review by grod220 — APPROVED** [review]
