### PR TITLE
fix: only allow voting in current results when able

### LINKED ISSUE #2357: LQT round page: hide 'vote' column in current results table
Hide 'vote' column in the "current results table" if:
1. User voted already
2. The epoch is over

Image

### PR DESCRIPTION
**Pull request by vacekj**
fixes #2357

### CODE REVIEW

File: apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx [hunk 1]
```diff
@@ -48,8 +49,13 @@ export const CurrentVotingResults = observer(({ epoch }: CurrentVotingResultsPro
     sortDirection: sortBy.direction,
   });
 
-  // TODO: `canVote` should be true when connected and has delUM for this epoch
-  const canVote = connected;
+  const { isVoted, isDelegated, isEnded } = useVotingInfo();
```
[the remark this answers is not in the document]
Comment (vacekj) [reply apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx:52]: afaik useVotingInfo uses the current epoch by default, which is what we want here.

[the remark this answers is not in the document]
Comment (VanishMax) [reply apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx:52]: But why? We're talking about the round page for a specific epoch. Then we check if a user can vote for this specific, not current, epoch

[the remark this answers is not in the document]
Comment (vacekj) [reply apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx:52]: You're right - my mistake. Will fix.

File: apps/veil/src/pages/tournament/api/use-tournament-votes.ts [hunk 2]
```diff
@@ -4,12 +4,13 @@ import { AddressIndex } from '@penumbra-zone/protobuf/penumbra/core/keys/v1/keys
...
 import { penumbra } from '@/shared/const/penumbra';
 import { useRefetchOnNewBlock } from '@/shared/api/compact-block';
+import { TournamentVotesResponse_Vote } from '@penumbra-zone/protobuf/penumbra/view/v1/view_pb';
 
 export const useTournamentVotes = (epoch?: number, disabled?: boolean) => {
   const { connected, subaccount } = connectionStore;
   const enabled = connected && !!epoch;
 
-  const query = useQuery({
+  const query = useQuery<TournamentVotesResponse_Vote[]>({
```
Comment (TalDerei) [inline apps/veil/src/pages/tournament/api/use-tournament-votes.ts:13]: comment: proto type is infered here, doesn't need to be strictly typed

File: apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx [hunk 3]
```diff
@@ -48,8 +49,13 @@ export const CurrentVotingResults = observer(({ epoch }: CurrentVotingResultsPro
...
+
+  /* A user can vote if they:
+   * - have enough delUM
+   * - epoch hasn't ended yet
+   * - user hasn't voted already for this epoch */
+  const canVote = connected && !isEnded && isDelegated && !isVoted;
```
Comment (TalDerei) [inline apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx:58]: comment: vote button seems to disappear and then pop back up after epoch has ended.

----------

Screenshot 2025-05-15 at 2 27 23 PM

**Review by TalDerei — CHANGES_REQUESTED** [review]

File: apps/veil/src/pages/tournament/api/use-tournament-votes.ts (hunk 2 above)
Comment (cronokirby) [reply apps/veil/src/pages/tournament/api/use-tournament-votes.ts:13]: I would also rather see the top level function annotated with `UseQueryResult<...>` so that you can see this without inspecting the function body.

Comment (TalDerei) [reply apps/veil/src/pages/tournament/api/use-tournament-votes.ts:13]: > I would also rather see the top level function annotated with `UseQueryResult<...>` so that you can see this without inspecting the function body.

impartial; this isn't blocking for me

File: apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx (hunk 3 above)
Comment (vacekj) [reply apps/veil/src/pages/tournament/ui/round/current-voting-results/index.tsx:58]: Fixed by passing in the correct epoch.

**Review by TalDerei — APPROVED** [review]

**Comment by TalDerei** [comment]
👍
