### PR TITLE
fix install bug

### LINKED ISSUE #1191: Install Prax bug
In an incognito window visit https://app.testnet.penumbra.zone/. The web app is not able to detect install status of the extension and requests to connect instead:

Screenshot 2024-05-28 at 5 36 33 PM

The UI should instead display a link to go to the chrome store to download the app.

### PR DESCRIPTION
**Pull request by turbocrime**
fixes #1191 

loaders block the entire page until complete, unless they throw locally. loaders were manually calling a connection failure test in order to mimic the layoutloader connection test, but this was incomplete, resulting inaccurate state detection in some situations.

removing those tests resulted in loader use of a client blocking the page, and blocking any thrown error from generating an error page, until the transport timeout. this obscured any early-thrown prax connection failure, and presented the last loader error, which was also misdetected.

so this pr reimplements a more complete temporary solution to fail loaders. ultimately, we should prefer a transport provider and connect-query.

also cleans up the client package a bit, makes the error page ui consistent

some work was also done on the protobuf package, as #1209, it now re-exports service definitions as well as the registry.

### CODE REVIEW

**Comment by turbocrime** [comment]
relevant #1202

File: packages/client/src/prax.ts [hunk 1]
```diff
@@ -15,82 +17,99 @@ const prax_id = 'lkpmkhpnhknhmibgnmmhdhgdilepfghe';
...
-  getPraxManifest().then(
-    () => true,
-    () => false,
+export const getPraxManifest = async () => {
+  const json = await fetch(prax_manifest).then(
+    ({ ok, json }) => (ok ? json : Promise.reject(new PraxNotInstalledError())),
+    () => Promise.reject(new PraxNotInstalledError()),
   );
+  return (await json()) as JsonValue;
+};
```
Comment (turbocrime) [inline packages/client/src/prax.ts:52]: manifest fetch is used to confirm install. extension asset fetch has a different behavior in incognito mode that was not resolving properly.

File: packages/client/src/prax.ts [hunk 2]
```diff
@@ -15,82 +17,99 @@ const prax_id = 'lkpmkhpnhknhmibgnmmhdhgdilepfghe';
...
 
-export const throwIfPraxNotInstalled = async () => {
-  const isInstalled = await isPraxInstalled();
-  if (!isInstalled) throw new PraxNotInstalledError('Prax not installed');
+export const getPraxPort = async () => {
+  await throwIfPraxNotInstalled();
+  throwIfPraxNotAvailable();
+  return window[PenumbraSymbol]![prax_origin]!.connect();
 };
```
Comment (turbocrime) [inline packages/client/src/prax.ts:58]: ideally the page developer should be expected to confirm connection before creating a transport with this passed as `getPort`.

there is some wiggle-room as transport doesn't fail until it passes the configured timeout (default 10s) during which connection may init and succeed this promise.

File: apps/minifront/src/abort-loader.ts [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+ * Resolves fast if Prax is connected, or rejects if Prax is not connected after
+ * timeout. This is a temporary solution until loaders properly await Prax
+ * connection.
+ *
+ * @param timeout maximum wait in milliseconds (default 500)
+ */
+export const abortLoader = async (timeout = 500): Promise<void> => {
+  await throwIfPraxNotInstalled();
+  (await retry(() => isPraxConnected(), timeout)) || throwIfPraxNotConnected();
+};
```
Comment (grod220) [inline apps/minifront/src/abort-loader.ts:34]: Adds clarity if expanded:

```ts
  const isConnected = await retry(isPraxConnected, timeout);
  if (!isConnected) {
    throwIfPraxNotConnected();
  }
```

File: apps/minifront/src/abort-loader.ts [hunk 4]
```diff
@@ -0,0 +1,34 @@
+import {
+  isPraxConnected,
+  throwIfPraxNotConnected,
+  throwIfPraxNotInstalled,
+} from '@penumbra-zone/client/prax';
+
+const retry = (fn: () => boolean, ms: number) =>
+  new Promise<boolean>(resolve => {
+    if (fn()) resolve(true);
```
Comment (grod220) [inline apps/minifront/src/abort-loader.ts:9]: We should exit function if success right? aka

```ts
    if (fn()) {
      resolve(true);
      return;
    }
```

File: apps/minifront/src/abort-loader.ts [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+    const interval = setInterval(
+      () => {
+        if (!fn()) return;
+        clearInterval(interval);
+        resolve(true);
+      },
+      Math.max(ms / 10, 50),
```
Comment (grod220) [inline apps/minifront/src/abort-loader.ts:16]: Can you add some documentation about this:

```diff
const retry = (fn: () => boolean, ms: number) => {
+  const retryDelay = Math.max(ms / 10, 50); // do not retry faster than 50ms
...
- Math.max(ms / 10, 50),
+ retryDelay
```

File: apps/minifront/src/components/extension-not-connected.tsx [hunk 6]
```diff
@@ -62,15 +56,15 @@ export const ExtensionNotConnected = () => {
     <>
       <HeadTag />
       <Toaster />
-      <SplashPage title='Welcome to Penumbra'>
+      <SplashPage title='Connect to Penumbra'>
```
Comment (grod220) [inline apps/minifront/src/components/extension-not-connected.tsx:59]: Probably `Connect to Penumbra Wallet`?

File: apps/minifront/src/components/extension-not-connected.tsx [hunk 7]
```diff
@@ -62,15 +56,15 @@ export const ExtensionNotConnected = () => {
...
         <div className='flex items-center justify-between gap-[1em] text-lg'>
           <div>To get started, connect the Penumbra Chrome extension.</div>
           {!result ? (
-            <Button variant='gradient' onClick={() => void request()} className='px-4'>
```
Comment (grod220) [inline apps/minifront/src/components/extension-not-connected.tsx:69]: Were there design changes? Can you share screenshots on changes?

File: apps/minifront/src/components/header/top-row.tsx [hunk 8]
```diff
@@ -13,20 +13,18 @@ import { PagePath } from '../metadata/paths';
...
 // Henry (@hdevalence) and thus tied to his Discord account, so reach out to him
 // if there are any problems with this link.
 const WEB_EXT_FEEDBACK_DISCORD_CHANNEL = 'https://discord.gg/XDNcrhKVwV';
 
 export const TopRow = () => {
-  const { isInstalled, isConnected } = useLoaderData() as LayoutLoaderResult;
   const [chainId, setChainId] = useState<string | undefined>();
 
   useEffect(() => {
-    if (isInstalled && isConnected) void getChainId().then(setChainId);
```
Comment (grod220) [inline apps/minifront/src/components/header/top-row.tsx:28]: Is there a reason why we don't need this guard anymore? Is it now impossible to get this component unless already connected?

File: packages/client/src/prax.ts (hunk 1 above)
Comment (grod220) [inline packages/client/src/prax.ts:52]: let's not mix async await and then() syntax here. Also, don't need to do Promise.reject() with async functions. Maybe something like:


```ts
export const getPraxManifest = async (): Promise<JsonValue> => {
  try {
    const response = await fetch(prax_manifest);
    if (!response.ok) {
      throw new PraxNotInstalledError();
    }
    return await response.json() as JsonValue;
  } catch (error) {
    throw new PraxNotInstalledError();
  }
};

```

File: packages/client/src/prax.ts
Comment (grod220) [inline packages/client/src/prax.ts:1]: Related to: https://github.com/penumbra-zone/web/issues/825, but I think this could use some encapsulation:

```ts
export class PraxWallet implements PenumbraWallet {
  transport: Transport | undefined = undefined;

  constructor() {}

  isAvailable(): boolean {}

  isInstalled(): boolean {}

  createWalletClient<T extends ServiceType>(serviceType: T): PromiseClient<T> {
    if (this.transport) return this.transport;
    // else instantiate...
  }

}
```

File: packages/client/src/prax.ts [hunk 9]
```diff
@@ -15,82 +17,99 @@ const prax_id = 'lkpmkhpnhknhmibgnmmhdhgdilepfghe';
...
+
+export class PraxManifestError extends Error {
+  constructor(
+    message = 'Incorrect Prax manifest href',
+    public opts?: ErrorOptions,
+  ) {
+    super(message, opts);
+    this.name = 'PraxManifestError';
+  }
+}
```
Comment (grod220) [inline packages/client/src/prax.ts:115]: Can we move these to an error file?

**Review by grod220 — COMMENTED** [review]
I feel a bit uneasy about the `abortLoader()` pattern. It feels a bit too hacky of a workaround.

Isn't the main thing we want is simply to redirect if the user is not connected to Prax? Loaders can return [redirect responses](https://reactrouter.com/en/main/fetch/redirect). Aka, change all of these:

```diff
- await throwIfPraxNotConnectedTimeout();
+ await redirectIfPraxNotConnectedTimeout(); // 302 response
``` 

which sends it to our connect page. Then the order would not be important and the first to resolve is the first to issue the redirect.

**Comment by turbocrime** [comment]
> I feel a bit uneasy about the `abortLoader()` pattern. It feels a bit too hacky of a workaround.

It's hacky, and it's a workaround, but it is equivalent to the current state of things - calling `throwIfPraxNotConnected` - but it is standardized and complete.
 
> Isn't the main thing we want is simply to redirect if the user is not connected to Prax? Loaders can return [redirect responses](https://reactrouter.com/en/main/fetch/redirect). Aka, change all of these:
> 
> ```diff
> - await throwIfPraxNotConnectedTimeout();
> + await redirectIfPraxNotConnectedTimeout(); // 302 response
> ```
> 
> which sends it to our connect page. Then the order would not be important and the first to resolve is the first to issue the redirect.

ah, okay. does the redirect certainly not block until all loaders complete? this would also require new routes in minifront as a sort of "onboarding flow". which is essentially a new feature so i'm inclined to call this out of scope, this pr is a minimal solution

File: apps/minifront/src/components/extension-not-connected.tsx (hunk 7 above)
Comment (turbocrime) [reply apps/minifront/src/components/extension-not-connected.tsx:69]: the error pages all had different font sizes and such. i just made styling between all equivalent.

File: packages/client/src/prax.ts
Comment (turbocrime) [reply packages/client/src/prax.ts:1]: encapsulation is out of scope here and work is in #1200

File: apps/minifront/src/components/header/top-row.tsx (hunk 8 above)
Comment (turbocrime) [reply apps/minifront/src/components/header/top-row.tsx:28]: this header doesn't appear on the connection error pages, which should be the only thing that appears if it's not possible to connect to the extension.

**Review by grod220 — APPROVED** [review]
Once we move away from loaders, the `abortLoader()` can get scrapped. However, this does illuminate an issue with our API. Other consumers will need to have a way to cleanly await and definitively know whether the extension is installed or not.

**Comment by turbocrime** [comment]
>Other consumers will need to have a way to cleanly await and definitively know whether the extension is installed or not.

this is surfaced by the page global, but the loaders as written expect to create and use a client without respecting that status.
