### PR TITLE
fix unknownAssetId bugs

### LINKED ISSUE #1107: passet rendering bug
See account balance using testnet whale: https://rustdoc.penumbra.zone/main/penumbra_keys/test_keys/constant.SEED_PHRASE.html

Should reflect pill design as other assets (and likely use identicon).

Screenshot 2024-05-14 at 5 06 48 AM

### LINKED ISSUE #1108: Unknown asset selected bug
Use testnet whale: https://rustdoc.penumbra.zone/main/penumbra_keys/test_keys/constant.SEED_PHRASE.html

and go to /send route. Likely related to: https://github.com/penumbra-zone/web/issues/1107

Screenshot 2024-05-14 at 5 08 14 AM

### PR DESCRIPTION
**Pull request by Valentine1898**
close #1107 & close #1108

**1. Dashboard**
Before:
image
After:
image
<hr>

**2. Send**
Before:
image
After:
image
<hr>

**3. Tx page**
Before:
image
After:
image
<hr>

### CODE REVIEW

File: apps/minifront/src/state/send.ts [hunk 1]
```diff
@@ -152,10 +152,11 @@ export const amountMoreThanBalance = (
    */
   amountInDisplayDenom: string,
 ): boolean => {
-  if (asset.balanceView?.valueView.case !== 'knownAssetId')
-    throw new Error('unknown asset selected');
```
Comment (Valentine1898) [inline apps/minifront/src/state/send.ts:156]: We filter out unknown assets for ibc and swaps, but I believe there is no reason to disallow sending unknown assets

File: packages/ui/components/ui/tx/view/value/index.tsx [hunk 2]
```diff
@@ -30,62 +31,47 @@ export const ValueViewComponent = ({
...
+            {variant === 'equivalent' && <>~ </>}
+            {formattedAmount}
+          </span>
+        )}
+        {showDenom && (
+          <span className='truncate font-mono text-xs text-muted-foreground'>{symbol}</span>
+        )}
+      </div>
+    </Pill>
+  );
```
Comment (grod220) [inline packages/ui/components/ui/tx/view/value/index.tsx:55]: Can you make this a separate component instead of an inline function?

**Review by grod220 — APPROVED** [review]
👍 

> Not relevant to this PR, but maybe we don't need to show zero balances?

Good idea, can you create an issue?

**Review by TalDerei — APPROVED** [review]
