### PR TITLE
Fix issue with how error splash page was rendered

### LINKED ISSUE #960: Error splash screen render bug
We seemed to have had a regression from the work done here: https://github.com/penumbra-zone/web/pull/752

Our error splash page seems to be interleaved with our assets table now:

https://github.com/penumbra-zone/web/assets/16624263/7b28b6cd-ffa0-4c4e-8fca-20a1f746b356

### PR DESCRIPTION
**Pull request by jessepinho**
## Before (from #960)
https://github.com/penumbra-zone/web/assets/16624263/7b28b6cd-ffa0-4c4e-8fca-20a1f746b356

## After
image

Closes #960

### CODE REVIEW

File: apps/minifront/src/components/root-router.tsx [hunk 1]
```diff
@@ -34,12 +34,10 @@ export const rootRouter = createHashRouter([
             index: true,
             loader: AssetsLoader,
             element: <AssetsTable />,
-            errorElement: <ErrorBoundary />,
```
Comment (jessepinho) [inline apps/minifront/src/components/root-router.tsx:37]: Adding error boundaries lower down in the route tree means that the error boundary will render _within_ that route's `<Outlet />`. I've removed these so that all errors bubble up to the top-level boundary.

**Review by grod220 — APPROVED** [review]
