### PR TITLE
fix(veil): #2153: consistent x axis

### LINKED ISSUE #2153: x-axis on trading view chart cutting off dates
we should ensure more consistent spacing and rendering information on the x-axis of the trading view chart.

-----------------------

https://github.com/user-attachments/assets/574bf84c-824d-4990-87d2-ae95e5ff4fa2

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #2153 

The default Trading View behavior without using `.fitContent()` appears to be just what we need. Time frames like '1m', '15m', '1h', '4h', '1d' look very good with consistent bar width. The '1w' and '1mo` time frames lack data a little, but generally good to look consistent.

### CODE REVIEW

File: apps/veil/src/pages/trade/ui/chart.tsx [hunk 1]
```diff
@@ -225,21 +224,9 @@ const ChartData = observer(({ candles }: { candles: CandleWithVolume[] }) => {
...
 
-  // Handle window resize to re-fit content
-  useEffect(() => {
-    const handleResize = () => {
-      if (chartRef.current) {
-        chartRef.current.timeScale().fitContent();
-      }
-    };
-    window.addEventListener('resize', handleResize);
-    return () => window.removeEventListener('resize', handleResize);
```
Comment (VanishMax) [inline apps/veil/src/pages/trade/ui/chart.tsx:240]: this was only making the chart jump unnecessarily

**Review by JasonMHasperhoven — APPROVED** [review]

**Review by TalDerei — APPROVED** [review]
