### PR TITLE
fix: #657: stop truncating metadata symbols

### LINKED ISSUE #657: Use style for truncation insted of string manipulation
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

`text-overflow: ellipsis;` provides automatic truncation that is dynamic to the bounding box, but several places in the repo we implement this behavior in javascript and create strings with ellipses.

in some cases we even have both active on the same element

Screenshot 2024-03-01 at 20 33 41

instead of doing things the hard way, we should just use the style behavior in most cases.

if we have a *specific format* we want to display, in that case we *should not truncate*

### PR DESCRIPTION
**Pull request by VanishMax**
Closes #657 

Removed metadata symbol trimming from wasm and added max-width to the `ValueComponent` with the native tooltip, so users can always access the asset symbol.

image

### CODE REVIEW

**Comment by Valentine1898** [comment]
This affects some other ui components
image

It is also necessary to bump indexed-db version, otherwise metadata that is already stored in the DB will not be updated

**Comment by VanishMax** [comment]
@Valentine1898 thanks for noting the issues. Fixed multiple places with incorrect truncation + improved the Dialog component for mobile screens

File: packages/storage/src/indexed-db/config.ts [hunk 1]
```diff
@@ -2,4 +2,4 @@
  * The version number for the IndexedDB schema. This version number is used to manage
  * database upgrades and ensure that the correct schema version is applied.
  */
-export const IDB_VERSION = 44;
+export const IDB_VERSION = 45;
```
Comment (Valentine1898) [inline packages/storage/src/indexed-db/config.ts:5]: To clarify, this will cause mainnet users must sync again after updating the extension in chrome store. Should we already consider indexed-db migrations without data loss?

**Review by Valentine1898 — APPROVED** [review]
LGTM

File: packages/storage/src/indexed-db/config.ts (hunk 1 above)
Comment (grod220) [reply packages/storage/src/indexed-db/config.ts:5]: Think we are ok for now, syncing is very fast with the low block height at the moment
